# Fundo (Mantido)
background #141414

# Texto Principal (Agora é o VERDE antigo #afb979)
foreground #afb979

# Cursor (Mantido branco puro para contraste)
cursor #ffffff
selection_background #303030
selection_foreground #141414

# Cores Pretas/Cinzas (Mantidas)
color0 #141414
color8 #262626

# Vermelhos (Mantidos)
color1 #c06c43
color9 #dd7c4c

# VERDES (Agora são o BRANCO antigo #feffd3)
color2 #feffd3
color10 #feffd3

# Amarelos (Mantidos)
color3 #c2a86c
color11 #e1c47d

# Azuis (Mantidos)
color4 #444649
color12 #5a5d61

# Magentas (Estes já eram meio esverdeados, mantive original)
color5 #b4be7b
color13 #d0db8e

# Cyanos (Mantidos)
color6 #778284
color14 #8a989a

# BRANCOS (Agora são os VERDES antigos)
color7 #afb979
color15 #cbd88c
