# --- CORREÇÃO DO FUNDO ---
# Estava #282a36 (Roxo), mudamos para #000000 (Preto) para a transparência funcionar
background #000000
background_opacity 0.8

# --- RESTO DO TEMA NEON ---
foreground #ffffff
selection_background #ff79c6
selection_foreground #000000
url_color #8be9fd
cursor #ff79c6
cursor_text_color #000000

# Preto e Cinza (UI)
color0  #21222c
color8  #6272a4

# Vermelho
color1  #ff5555
color9  #ff6e6e

# Verde
color2  #50fa7b
color10 #69ff94

# Amarelo
color3  #f1fa8c
color11 #ffffa5

# Roxo
color4  #bd93f9
color12 #d6acff

# Rosa (Magenta)
color5  #ff79c6
color13 #ff92df

# Ciano
color6  #8be9fd
color14 #a4ffff

# Branco
color7  #f8f8f2
color15 #ffffff
